"""
Auto-generated model cards for trained BreezeML models.

A model card is a short, honest markdown document describing what a model
was trained on, how it was evaluated, which decisions the pipeline made,
and what its known limitations are. Inspired by "Model Cards for Model
Reporting" (Mitchell et al., 2019).
"""
from __future__ import annotations

from ._narrate import narrate

__all__ = ["card"]


def _metrics_table(report: dict) -> list[str]:
    lines = ["| Metric | Value |", "|---|---|"]
    for key, value in report.items():
        if isinstance(value, (int, float)) and value is not None:
            lines.append(f"| {key} | {value:.4f} |" if isinstance(value, float) else f"| {key} | {value} |")
    return lines


def card_text(model) -> str:
    """Render the model card for a trained EasyModel as markdown."""
    meta = getattr(model, "meta", None)
    if not meta:
        raise ValueError(
            "This model has no training metadata. Model cards are available for "
            "models trained with breezeml.fit / auto / classify / regress (v0.4+)."
        )

    profile = meta.get("profile", {})
    task = meta.get("task", "unknown")
    target = profile.get("target", getattr(model, "target", "?"))

    lines = [f"# Model Card: {meta.get('estimator', 'Model')} for '{target}'", ""]
    lines.append(f"*Generated by BreezeML {meta.get('breezeml_version', '?')} "
                 f"on {meta.get('trained_at', '?')}*")
    lines.append("")

    # Overview
    lines.append("## Overview")
    lines.append("")
    lines.append(f"- **Task:** {task}")
    if meta.get("task_reason"):
        lines.append(f"- **Task detection:** {meta['task_reason']}")
    lines.append(f"- **Estimator:** {meta.get('estimator')}")
    params = meta.get("estimator_params") or {}
    if params:
        param_str = ", ".join(f"{k}={v}" for k, v in sorted(params.items()))
        lines.append(f"- **Non-default parameters:** {param_str}")
    lines.append(f"- **Random seed:** {meta.get('random_state', 42)} (fully reproducible)")
    lines.append("")

    # Training data
    lines.append("## Training Data")
    lines.append("")
    lines.append(f"- **Rows:** {profile.get('n_rows'):,}")
    lines.append(f"- **Features:** {profile.get('n_features')} "
                 f"({len(profile.get('numeric_columns', []))} numeric, "
                 f"{len(profile.get('categorical_columns', []))} categorical)")
    lines.append(f"- **Missing cells:** {profile.get('missing_pct', 0)}%")
    if profile.get("columns_with_missing"):
        cols = ", ".join(f"`{c}` ({n})" for c, n in profile["columns_with_missing"].items())
        lines.append(f"- **Columns with missing values:** {cols}")
    if profile.get("class_counts"):
        lines.append(f"- **Target classes:** {profile.get('target_nunique')}")
        if profile.get("imbalance_ratio"):
            lines.append(f"- **Class imbalance ratio:** {profile['imbalance_ratio']}:1")
    lines.append("")

    # Evaluation
    lines.append("## Evaluation")
    lines.append("")
    holdout = int(meta.get("test_size", 0.2) * 100)
    split_kind = "stratified" if meta.get("stratified") else "random"
    lines.append(f"Metrics computed on a {split_kind} {holdout}% holdout set "
                 f"(never seen during training).")
    lines.append("")
    report = meta.get("report")
    if report:
        lines.extend(_metrics_table(report))
    else:
        lines.append("*No evaluation report captured.*")
    lines.append("")

    # Pipeline decisions (teaching narration)
    lines.append("## Pipeline Decisions")
    lines.append("")
    for decision in narrate(meta):
        lines.append(f"- {decision}")
    lines.append("")

    # Limitations
    lines.append("## Limitations & Caveats")
    lines.append("")
    caveats = []
    n_rows = profile.get("n_rows", 0)
    if n_rows < 200:
        caveats.append(
            f"Small dataset ({n_rows} rows): holdout metrics are high-variance. "
            "Re-validate with cross-validation before deployment."
        )
    if profile.get("imbalance_ratio") and profile["imbalance_ratio"] >= 3:
        caveats.append(
            "Significant class imbalance: prefer macro F1 / per-class recall over accuracy."
        )
    if profile.get("missing_pct", 0) > 20:
        caveats.append(
            "Over 20% of cells were imputed; predictions lean heavily on imputation assumptions."
        )
    caveats.append(
        "The model has only seen this dataset's distribution. Data drift at prediction "
        "time (new categories, shifted ranges) will silently degrade quality."
    )
    caveats.append(
        "No fairness audit was performed. If predictions affect people, evaluate per-group "
        "metrics before use."
    )
    for caveat in caveats:
        lines.append(f"- {caveat}")
    lines.append("")

    # Reproducibility
    lines.append("## Reproducibility")
    lines.append("")
    lines.append("Run `breezeml.export(model, \"train.py\")` to get a standalone "
                 "scikit-learn script that reproduces this exact pipeline with no "
                 "breezeml dependency.")
    lines.append("")

    return "\n".join(lines)


def card(model, path: str | None = None) -> str:
    """Generate a model card.

    Parameters
    ----------
    model : EasyModel
        A model trained with breezeml v0.4+ core API.
    path : str, optional
        If given, write the markdown card to this file.

    Returns
    -------
    str
        The model card as markdown text.
    """
    text = card_text(model)
    if path:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
    return text
