"""
One-line deployment for trained BreezeML models.

``breezeml.deploy(model, "my_api/")`` writes a complete, self-contained
serving directory:

    my_api/
    |-- model.joblib      # the raw sklearn pipeline (no breezeml needed)
    |-- app.py            # FastAPI serving app
    |-- requirements.txt  # minimal runtime deps
    |-- Dockerfile        # container build
    `-- README.md         # how to run it

The saved artifact is the *raw scikit-learn pipeline*, so the deployment
has zero breezeml dependency.
"""
from __future__ import annotations

import os

import joblib

__all__ = ["deploy", "to_onnx"]


_APP_TEMPLATE = '''"""
FastAPI serving app generated by BreezeML.

Run locally:
    uvicorn app:app --host 0.0.0.0 --port 8000
"""
import json
import os
from collections import deque

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException

MODEL_PATH = "model.joblib"
REFERENCE_PATH = "reference.json"
TARGET = {target!r}
TASK = {task!r}
FEATURE_COLUMNS = {feature_columns!r}
DRIFT_BUFFER_SIZE = 1000

app = FastAPI(
    title="{title}",
    description="Model serving API generated by BreezeML.",
    version="1.0.0",
)
pipeline = joblib.load(MODEL_PATH)
REFERENCE = json.load(open(REFERENCE_PATH)) if os.path.exists(REFERENCE_PATH) else None
_recent = deque(maxlen=DRIFT_BUFFER_SIZE)


@app.get("/")
def info():
    endpoints = {{"POST /predict": "send a JSON list of records"}}
    if REFERENCE:
        endpoints["GET /drift"] = "data drift report over recent requests"
    return {{
        "model": type(pipeline.named_steps.get("model", pipeline)).__name__,
        "task": TASK,
        "target": TARGET,
        "features": FEATURE_COLUMNS,
        "endpoints": endpoints,
    }}


@app.get("/health")
def health():
    return {{"status": "ok"}}


@app.post("/predict")
def predict(records: list[dict]):
    if not records:
        raise HTTPException(status_code=400, detail="Empty request body.")
    df = pd.DataFrame(records)
    if FEATURE_COLUMNS:
        missing = [c for c in FEATURE_COLUMNS if c not in df.columns]
        if missing:
            raise HTTPException(
                status_code=422,
                detail=f"Missing feature columns: {{missing}}",
            )
        df = df[FEATURE_COLUMNS]
    try:
        preds = pipeline.predict(df)
    except Exception as exc:
        raise HTTPException(status_code=422, detail=f"Prediction failed: {{exc}}")
    _recent.extend(df.to_dict(orient="records"))
    return {{"predictions": [_to_native(p) for p in preds]}}


@app.get("/drift")
def drift_report():
    """PSI-based drift report: recent request data vs training reference."""
    if REFERENCE is None:
        raise HTTPException(status_code=404, detail="No reference distributions were exported.")
    if len(_recent) < 30:
        return {{"status": "insufficient_data", "rows_buffered": len(_recent),
                 "detail": "Need at least 30 predictions to assess drift."}}

    df = pd.DataFrame(list(_recent))
    columns = {{}}
    drifted = []
    for col, ref in REFERENCE.get("numeric", {{}}).items():
        if col not in df.columns:
            continue
        values = pd.to_numeric(df[col], errors="coerce").dropna().to_numpy(dtype=float)
        if len(values) == 0:
            continue
        edges = np.asarray(ref["bin_edges"], dtype=float)
        counts, _ = np.histogram(np.clip(values, edges[0], edges[-1]), bins=edges)
        score = _psi(ref["bin_props"], counts / max(counts.sum(), 1))
        columns[col] = {{"psi": round(score, 4), "status": _status(score)}}
    for col, ref in REFERENCE.get("categorical", {{}}).items():
        if col not in df.columns:
            continue
        props = df[col].dropna().astype(str).value_counts(normalize=True)
        cats = list(ref.keys())
        unseen = float(sum(p for c, p in props.items() if c not in ref))
        score = _psi([ref[c] for c in cats] + [1e-4],
                     [float(props.get(c, 0.0)) for c in cats] + [unseen])
        columns[col] = {{"psi": round(score, 4), "status": _status(score),
                         "unseen_category_share": round(unseen, 4)}}
    drifted = [c for c, r in columns.items() if r["status"] == "drift"]
    return {{
        "drifted": bool(drifted),
        "drifted_columns": drifted,
        "columns": columns,
        "rows_checked": len(df),
    }}


def _psi(ref_props, new_props):
    ref = np.clip(np.asarray(ref_props, dtype=float), 1e-4, None)
    new = np.clip(np.asarray(new_props, dtype=float), 1e-4, None)
    ref, new = ref / ref.sum(), new / new.sum()
    return float(np.sum((new - ref) * np.log(new / ref)))


def _status(score):
    return "drift" if score >= 0.25 else ("warning" if score >= 0.10 else "ok")


def _to_native(value):
    """Convert numpy scalars to JSON-safe Python types."""
    if hasattr(value, "item"):
        return value.item()
    return value
'''

_DOCKERFILE = """FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model.joblib app.py reference.jso[n] ./

EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
"""
_COMPOSE_TEMPLATE = """services:
  {service_name}:
    build: .
    ports:
      - "{host_port}:8000"
    restart: unless-stopped
"""

_REQUIREMENTS = """fastapi>=0.100
uvicorn>=0.23
scikit-learn>=1.3
pandas>=1.5
joblib>=1.2
"""

_README_TEMPLATE = """# {title}

Model serving API generated by BreezeML. No breezeml dependency at runtime.

## Run locally

```bash
pip install -r requirements.txt
uvicorn app:app --host 0.0.0.0 --port 8000
```

## Run with Docker

```bash
docker build -t {docker_tag} .
docker run -p 8000:8000 {docker_tag}
```
{compose_section}
## Predict

```bash
curl -X POST http://localhost:8000/predict \\
  -H "Content-Type: application/json" \\
  -d '{example_payload}'
```

Interactive docs: http://localhost:8000/docs
"""


def _feature_columns(model) -> list[str]:
    meta = getattr(model, "meta", None) or {}
    profile = meta.get("profile", {})
    return list(profile.get("numeric_columns", [])) + list(profile.get("categorical_columns", []))


def _example_payload(columns: list[str]) -> str:
    if not columns:
        return '[{"feature_1": 0.0}]'
    record = ", ".join(f'"{c}": 0.0' for c in columns[:6])
    return f"[{{{record}}}]"


def deploy(
    model,
    out_dir: str = "deployment",
    name: str = "breezeml-model",
    compose: bool = False,
    port: int = 8000,
) -> str:
    """Write a complete FastAPI + Docker serving directory for a trained model.

    Parameters
    ----------
    model : EasyModel or sklearn Pipeline
        Trained BreezeML model.
    out_dir : str
        Directory to create (files are overwritten if present).
    name : str
        App title / docker tag stem.
    compose : bool
        If True, also write a ``docker-compose.yml`` next to the Dockerfile
        so the service can be started with ``docker compose up``.
    port : int
        Host port to publish when ``compose=True`` (container always
        listens on 8000 internally).

    Returns
    -------
    str
        The output directory path.
    """
    pipeline = getattr(model, "pipeline", model)
    target = getattr(model, "target", "target")
    task = getattr(model, "task", "unknown")
    columns = _feature_columns(model)

    os.makedirs(out_dir, exist_ok=True)

    joblib.dump(pipeline, os.path.join(out_dir, "model.joblib"))

    # Reference distributions enable the /drift endpoint (v1.3+ models).
    reference = (getattr(model, "meta", None) or {}).get("reference")
    if reference:
        import json

        with open(os.path.join(out_dir, "reference.json"), "w", encoding="utf-8") as fh:
            json.dump(reference, fh)

    app_code = _APP_TEMPLATE.format(
        target=target,
        task=task,
        feature_columns=columns,
        title=name,
    )
    with open(os.path.join(out_dir, "app.py"), "w", encoding="utf-8") as fh:
        fh.write(app_code)

    with open(os.path.join(out_dir, "requirements.txt"), "w", encoding="utf-8") as fh:
        fh.write(_REQUIREMENTS)

    with open(os.path.join(out_dir, "Dockerfile"), "w", encoding="utf-8") as fh:
        fh.write(_DOCKERFILE)

    service_name = name.lower().replace(" ", "-")
    compose_section = ""
    if compose:
        compose_yaml = _COMPOSE_TEMPLATE.format(
            service_name=service_name,
            host_port=port,
        )
        with open(os.path.join(out_dir, "docker-compose.yml"), "w", encoding="utf-8") as fh:
            fh.write(compose_yaml)
        compose_section = f"""
## Run with Docker Compose

```bash
docker compose up --build
```

The API will be available at http://localhost:{port}.
"""

    readme = _README_TEMPLATE.format(
        title=name,
        docker_tag=service_name,
        compose_section=compose_section,
        example_payload=_example_payload(columns),
    )
    with open(os.path.join(out_dir, "README.md"), "w", encoding="utf-8") as fh:
        fh.write(readme)

    print(f"Deployment written to '{out_dir}/'")
    if compose:
        print(f"  Run: cd {out_dir} && docker compose up --build")
    else:
        print(f"  Run: cd {out_dir} && pip install -r requirements.txt && uvicorn app:app")
    return out_dir


def to_onnx(model, path: str = "model.onnx"):
    """Export a trained model to ONNX format (requires the [deploy] extra).

    Notes
    -----
    ONNX conversion supports most sklearn estimators but not all pipeline
    configurations. Install with: ``pip install breezeml[onnx]``.
    """
    try:
        from skl2onnx import to_onnx as _sk_to_onnx
    except ImportError as exc:
        raise ImportError(
            "ONNX export requires skl2onnx. Install with: pip install breezeml[onnx]"
        ) from exc

    pipeline = getattr(model, "pipeline", model)
    meta = getattr(model, "meta", None) or {}
    profile = meta.get("profile", {})
    if profile.get("categorical_columns"):
        raise ValueError(
            "ONNX export currently supports numeric-only pipelines. "
            "Your model uses one-hot encoded categorical columns."
        )

    import numpy as np

    n_features = profile.get("n_features")
    if n_features is None:
        raise ValueError("Model has no metadata; ONNX export needs a v0.4+ trained model.")

    sample = np.zeros((1, n_features), dtype=np.float32)
    onx = _sk_to_onnx(pipeline, sample)
    with open(path, "wb") as fh:
        fh.write(onx.SerializeToString())
    return path
