"""
One-line deployment for trained BreezeML models.

``breezeml.deploy(model, "my_api/")`` writes a complete, self-contained
serving directory:

    my_api/
    |-- model.joblib      # the raw sklearn pipeline (no breezeml needed)
    |-- app.py            # FastAPI serving app
    |-- requirements.txt  # minimal runtime deps
    |-- Dockerfile        # container build
    `-- README.md         # how to run it

The saved artifact is the *raw scikit-learn pipeline*, so the deployment
has zero breezeml dependency.
"""
from __future__ import annotations

import os

import joblib

__all__ = ["deploy", "to_onnx"]


_APP_TEMPLATE = '''"""
FastAPI serving app generated by BreezeML.

Run locally:
    uvicorn app:app --host 0.0.0.0 --port 8000
"""
import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException

MODEL_PATH = "model.joblib"
TARGET = {target!r}
TASK = {task!r}
FEATURE_COLUMNS = {feature_columns!r}

app = FastAPI(
    title="{title}",
    description="Model serving API generated by BreezeML.",
    version="1.0.0",
)
pipeline = joblib.load(MODEL_PATH)


@app.get("/")
def info():
    return {{
        "model": type(pipeline.named_steps.get("model", pipeline)).__name__,
        "task": TASK,
        "target": TARGET,
        "features": FEATURE_COLUMNS,
        "endpoints": {{"POST /predict": "send a JSON list of records"}},
    }}


@app.get("/health")
def health():
    return {{"status": "ok"}}


@app.post("/predict")
def predict(records: list[dict]):
    if not records:
        raise HTTPException(status_code=400, detail="Empty request body.")
    df = pd.DataFrame(records)
    if FEATURE_COLUMNS:
        missing = [c for c in FEATURE_COLUMNS if c not in df.columns]
        if missing:
            raise HTTPException(
                status_code=422,
                detail=f"Missing feature columns: {{missing}}",
            )
        df = df[FEATURE_COLUMNS]
    try:
        preds = pipeline.predict(df)
    except Exception as exc:
        raise HTTPException(status_code=422, detail=f"Prediction failed: {{exc}}")
    return {{"predictions": [_to_native(p) for p in preds]}}


def _to_native(value):
    """Convert numpy scalars to JSON-safe Python types."""
    if hasattr(value, "item"):
        return value.item()
    return value
'''

_DOCKERFILE = """FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model.joblib app.py ./

EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
"""

_REQUIREMENTS = """fastapi>=0.100
uvicorn>=0.23
scikit-learn>=1.3
pandas>=1.5
joblib>=1.2
"""

_README_TEMPLATE = """# {title}

Model serving API generated by BreezeML. No breezeml dependency at runtime.

## Run locally

```bash
pip install -r requirements.txt
uvicorn app:app --host 0.0.0.0 --port 8000
```

## Run with Docker

```bash
docker build -t {docker_tag} .
docker run -p 8000:8000 {docker_tag}
```

## Predict

```bash
curl -X POST http://localhost:8000/predict \\
  -H "Content-Type: application/json" \\
  -d '{example_payload}'
```

Interactive docs: http://localhost:8000/docs
"""


def _feature_columns(model) -> list[str]:
    meta = getattr(model, "meta", None) or {}
    profile = meta.get("profile", {})
    return list(profile.get("numeric_columns", [])) + list(profile.get("categorical_columns", []))


def _example_payload(columns: list[str]) -> str:
    if not columns:
        return '[{"feature_1": 0.0}]'
    record = ", ".join(f'"{c}": 0.0' for c in columns[:6])
    return f"[{{{record}}}]"


def deploy(model, out_dir: str = "deployment", name: str = "breezeml-model") -> str:
    """Write a complete FastAPI + Docker serving directory for a trained model.

    Parameters
    ----------
    model : EasyModel or sklearn Pipeline
        Trained BreezeML model.
    out_dir : str
        Directory to create (files are overwritten if present).
    name : str
        App title / docker tag stem.

    Returns
    -------
    str
        The output directory path.
    """
    pipeline = getattr(model, "pipeline", model)
    target = getattr(model, "target", "target")
    task = getattr(model, "task", "unknown")
    columns = _feature_columns(model)

    os.makedirs(out_dir, exist_ok=True)

    joblib.dump(pipeline, os.path.join(out_dir, "model.joblib"))

    app_code = _APP_TEMPLATE.format(
        target=target,
        task=task,
        feature_columns=columns,
        title=name,
    )
    with open(os.path.join(out_dir, "app.py"), "w", encoding="utf-8") as fh:
        fh.write(app_code)

    with open(os.path.join(out_dir, "requirements.txt"), "w", encoding="utf-8") as fh:
        fh.write(_REQUIREMENTS)

    with open(os.path.join(out_dir, "Dockerfile"), "w", encoding="utf-8") as fh:
        fh.write(_DOCKERFILE)

    readme = _README_TEMPLATE.format(
        title=name,
        docker_tag=name.lower().replace(" ", "-"),
        example_payload=_example_payload(columns),
    )
    with open(os.path.join(out_dir, "README.md"), "w", encoding="utf-8") as fh:
        fh.write(readme)

    print(f"Deployment written to '{out_dir}/'")
    print(f"  Run: cd {out_dir} && pip install -r requirements.txt && uvicorn app:app")
    return out_dir


def to_onnx(model, path: str = "model.onnx"):
    """Export a trained model to ONNX format (requires the [deploy] extra).

    Notes
    -----
    ONNX conversion supports most sklearn estimators but not all pipeline
    configurations. Install with: ``pip install breezeml[onnx]``.
    """
    try:
        from skl2onnx import to_onnx as _sk_to_onnx
    except ImportError as exc:
        raise ImportError(
            "ONNX export requires skl2onnx. Install with: pip install breezeml[onnx]"
        ) from exc

    pipeline = getattr(model, "pipeline", model)
    meta = getattr(model, "meta", None) or {}
    profile = meta.get("profile", {})
    if profile.get("categorical_columns"):
        raise ValueError(
            "ONNX export currently supports numeric-only pipelines. "
            "Your model uses one-hot encoded categorical columns."
        )

    import numpy as np

    n_features = profile.get("n_features")
    if n_features is None:
        raise ValueError("Model has no metadata; ONNX export needs a v0.4+ trained model.")

    sample = np.zeros((1, n_features), dtype=np.float32)
    onx = _sk_to_onnx(pipeline, sample)
    with open(path, "wb") as fh:
        fh.write(onx.SerializeToString())
    return path
