"""Build the BreezeML Playground notebook series as .ipynb files.

Each notebook teaches one strength of an honest ML workflow, using the
synthetic BreezeML Playground dataset on Kaggle. Run this script to
regenerate every notebook; push each with the Kaggle CLI.
"""

import json
from pathlib import Path

_n = [0]


def _id():
    _n[0] += 1
    return f"cell-{_n[0]:02d}"


def md(s):
    return {"cell_type": "markdown", "id": _id(), "metadata": {}, "source": s}


def code(s):
    return {"cell_type": "code", "id": _id(), "metadata": {},
            "execution_count": None, "outputs": [], "source": s}


LOADER = """import glob
import pandas as pd
import breezeml

def load(name):
    \"\"\"Find a playground file wherever Kaggle mounts the dataset.\"\"\"
    return pd.read_csv(glob.glob(f"/kaggle/input/**/{name}", recursive=True)[0])"""

INSTALL = code("%pip install -q breezeml")

FOOTER = md("""---

*This notebook is part of the **BreezeML Playground** series: small, honest
lessons in the parts of machine learning that quietly break real projects.
The data is synthetic and generated by an
[open script](https://www.kaggle.com/datasets/venomezviper/breezeml-playground),
so every pattern and trap in it was planted on purpose and can be inspected.*

- Library: [github.com/venomez-viper/breezeml](https://github.com/venomez-viper/breezeml)
- Questions welcome: [GitHub Discussions](https://github.com/venomez-viper/breezeml/discussions)
- `pip install breezeml`

*If this taught you something, an upvote helps the next person find it.*""")


NOTEBOOKS = {
    # ------------------------------------------------------------ 1: audit
    "find-the-leak": {
        "title": "Find the Leak Before It Finds You",
        "file": "nb1_find_the_leak.ipynb",
        "cells": [
            md("""# Find the Leak Before It Finds You

Here is the most expensive mistake in applied machine learning, and it does not look like a mistake at all.

You train a model. The score is excellent. Everyone is happy. Months later someone notices the model was quietly reading the answer key: a column that would not exist at prediction time, or an ID it memorized. The great score was fiction.

This is called **leakage**, and researchers have documented it in hundreds of published papers. It is not a beginner mistake. It is an everyone mistake.

This notebook plants two classic leaks in a churn dataset and shows how a data audit catches both in seconds.

*Turn Internet ON in the right sidebar so pip can install.*"""),
            INSTALL,
            md("""## The data: customer churn, straight from the warehouse

A telecom wants to predict which customers will cancel. Someone exported "everything we have" to a CSV. That phrase should already worry you."""),
            code(LOADER + """

df = load("churn_raw.csv")
df.head()"""),
            md("""## Train first, ask questions later (the usual workflow)

One line trains a leakage-safe pipeline. One line asks for the honest verdict."""),
            code("""model = breezeml.fit(df, "churned")
report = model.report(df)"""),
            md("""**STOP.** The score looked strong, and the report refused to approve it anyway. Let's see exactly why:"""),
            code("""audit = breezeml.audit(df, "churned")"""),
            md("""Two traps, both flagged:

**Trap 1: `customer_id`.** Just a row number. A model can memorize "customer 100241 churned" and score well on data it has seen, while learning nothing about churn. Like a student who memorizes that question 7's answer is C.

**Trap 2: `days_until_cancellation`.** Read that column name slowly. You only know the days until cancellation for customers who *already cancelled*. At prediction time, for a live customer, this column cannot exist. It is the answer wearing a costume. The audit caught it because that single column predicts the target almost perfectly on its own, which is exactly how leaks behave.

Real examples of trap 2 in the wild: "date_of_refund" in a refund-prediction model, "discharge_notes" in a hospital readmission model, "fraud_investigation_id" in a fraud model."""),
            md("""## Fix and retrain"""),
            code("""clean = df.drop(columns=["customer_id", "days_until_cancellation"])

model = breezeml.fit(clean, "churned")
report = model.report(clean)"""),
            md("""**SHIP.** The honest score is lower than the leaky one. That is not a loss. The leaky score was never real; this one will survive contact with production.

## What to remember

- If a column would not exist at prediction time, it is leakage. Delete it.
- ID columns are memorization bait. Delete them.
- The one-line habit that catches most of this: run `breezeml.audit(df, target)` before you trust any score.
- A score that drops after cleaning was never yours to begin with."""),
            FOOTER,
        ],
    },
    # -------------------------------------------------------- 2: imbalance
    "when-accuracy-lies": {
        "title": "When Accuracy Lies: Imbalanced Classes",
        "file": "nb2_when_accuracy_lies.ipynb",
        "cells": [
            md("""# When Accuracy Lies: Imbalanced Classes

A model that predicts "no fraud" for every single transaction is 99% accurate, and completely useless.

Whenever one outcome is much rarer than the other (fraud, churn, disease, machine failure), plain accuracy becomes a beautiful, misleading number. The rare cases are usually the entire point, and accuracy barely notices them.

This notebook shows the trap on churn data, then three honest tools: a summary that names the problem, a threshold tuned for the minority, and a threshold tuned for money.

*Turn Internet ON in the right sidebar.*"""),
            INSTALL,
            code(LOADER + """
from breezeml import imbalance

df = load("churn.csv")
print("churn rate:", df["churned"].mean().round(3))"""),
            md("""About 12% of customers churn. Name the problem precisely first:"""),
            code("""summary = imbalance.summary(df["churned"])"""),
            md("""## Train and look past accuracy

We train normally, then read the full evaluation instead of stopping at the first number."""),
            code("""model = breezeml.fit(df, "churned")
metrics = model.evaluate(df)"""),
            md("""Accuracy looks comfortable. But the question a business actually asks is: **of the customers who will churn, how many did we catch?** That is recall on the minority class, and with the default decision rule it is usually mediocre.

## Tool 1: move the threshold

A classifier outputs a probability. The default rule says "call it churn above 0.5." Nothing about 0.5 is sacred. For rare classes it is usually too strict. `tune_threshold` searches for the cutoff that maximizes F1 for the minority class:"""),
            code("""tuned = imbalance.tune_threshold(model, df, "churned", metric="f1")"""),
            md("""Lower threshold, more churners caught, a few more false alarms. Whether that trade is good depends on what mistakes cost, which brings us to the honest version of this decision.

## Tool 2: tune for money, not metrics

Suppose losing a churner costs \\$500 in lost revenue, while a retention offer sent to a false alarm costs \\$50. Missing a churner is 10x worse. The threshold should know that:"""),
            code("""costs = imbalance.cost_report(model, df, "churned", fp_cost=50, fn_cost=500)"""),
            md("""This is the number to bring to a meeting: the cutoff that minimizes real cost, with the expected cost per customer next to it.

## What to remember

- The rarer the positive class, the more accuracy flatters the model. Read minority recall.
- The 0.5 threshold is a default, not a law. Tune it for your metric, or better, your costs.
- One honest sentence beats one big number: "we catch X% of churners at the cost of Y false alarms per hundred customers." """),
            FOOTER,
        ],
    },
    # ------------------------------------------------------------ 3: drift
    "models-rot": {
        "title": "Your Model Will Rot: Catching Drift",
        "file": "nb3_models_rot.ipynb",
        "cells": [
            md("""# Your Model Will Rot: Catching Drift

A model is a snapshot of the world on the day you trained it. The world does not stay still.

Prices change, behavior shifts, a new product type appears. The model keeps confidently scoring away, on data that no longer looks like anything it studied. Nobody gets an error message. The predictions just quietly get worse.

This is **drift**, and this notebook shows how to catch it with one call, before your users catch it for you.

*Turn Internet ON in the right sidebar.*"""),
            INSTALL,
            md("""## Train on this quarter"""),
            code(LOADER + """
from breezeml import drift

df = load("churn.csv")
model = breezeml.fit(df, "churned")
report = model.report(df)"""),
            md("""SHIP. The model is sound for the world it was trained in. Note what BreezeML did silently: at training time it stored a fingerprint of every feature's distribution inside the model. That fingerprint is what makes the next step possible.

## Next quarter's customers arrive

Three months pass. A price increase rolled out, engagement patterns changed, and marketing launched a new "flex" contract. Here is the new batch to score:"""),
            code("""new_batch = load("churn_next_quarter.csv")
result = drift.check(model, new_batch)"""),
            md("""Three columns drifted, and one of them contains a category the model has never seen in its life (`flex`).

The number doing the work is **PSI** (population stability index). The intuition is simple: cut the training distribution into bins, drop the new data into the same bins, and measure how differently it lands. Rule of thumb: below 0.1 is calm, 0.1 to 0.25 deserves a look, above 0.25 the ground has moved.

## What do you do about it?

1. **Investigate before retraining.** Drift is information. A price increase changing `monthly_charges` is expected; `days_since_login` doubling might mean a tracking bug, not a behavior change. Retraining on buggy data makes things worse.
2. **Retrain when the drift is real** and reflects the new normal, with fresh labels.
3. **Monitor continuously.** If you deploy with `breezeml.deploy(model, "api/")`, the generated API serves a live `/drift` endpoint computing exactly this check on the last thousand requests. Rot detection built into the product, not a quarterly chore.

## What to remember

- A green test-set score has an expiry date printed in invisible ink.
- Check drift whenever a new scoring batch arrives, it costs one line.
- New categories are the loudest drift signal: the model literally has no idea what `flex` is."""),
            FOOTER,
        ],
    },
}


def main():
    out_dir = Path(__file__).parent / "notebooks"
    out_dir.mkdir(exist_ok=True)
    for slug, nb_def in NOTEBOOKS.items():
        nb = {
            "nbformat": 4,
            "nbformat_minor": 5,
            "metadata": {
                "kernelspec": {"display_name": "Python 3", "language": "python",
                               "name": "python3"},
                "language_info": {"name": "python", "version": "3.11"},
            },
            "cells": nb_def["cells"],
        }
        path = out_dir / nb_def["file"]
        path.write_text(json.dumps(nb, indent=1), encoding="utf-8")
        print(f"wrote {path.name}  ({nb_def['title']})")


if __name__ == "__main__":
    main()
