"""
FastAPI serving app generated by BreezeML.

Run locally:
    uvicorn app:app --host 0.0.0.0 --port 8000
"""
import json
import os
from collections import deque

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException

MODEL_PATH = "model.joblib"
REFERENCE_PATH = "reference.json"
TARGET = 'species'
TASK = 'classification'
FEATURE_COLUMNS = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
DRIFT_BUFFER_SIZE = 1000

app = FastAPI(
    title="breezeml-model",
    description="Model serving API generated by BreezeML.",
    version="1.0.0",
)
pipeline = joblib.load(MODEL_PATH)
REFERENCE = json.load(open(REFERENCE_PATH)) if os.path.exists(REFERENCE_PATH) else None
_recent = deque(maxlen=DRIFT_BUFFER_SIZE)


@app.get("/")
def info():
    endpoints = {"POST /predict": "send a JSON list of records"}
    if REFERENCE:
        endpoints["GET /drift"] = "data drift report over recent requests"
    return {
        "model": type(pipeline.named_steps.get("model", pipeline)).__name__,
        "task": TASK,
        "target": TARGET,
        "features": FEATURE_COLUMNS,
        "endpoints": endpoints,
    }


@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/predict")
def predict(records: list[dict]):
    if not records:
        raise HTTPException(status_code=400, detail="Empty request body.")
    df = pd.DataFrame(records)
    if FEATURE_COLUMNS:
        missing = [c for c in FEATURE_COLUMNS if c not in df.columns]
        if missing:
            raise HTTPException(
                status_code=422,
                detail=f"Missing feature columns: {missing}",
            )
        df = df[FEATURE_COLUMNS]
    try:
        preds = pipeline.predict(df)
    except Exception as exc:
        raise HTTPException(status_code=422, detail=f"Prediction failed: {exc}")
    _recent.extend(df.to_dict(orient="records"))
    return {"predictions": [_to_native(p) for p in preds]}


@app.get("/drift")
def drift_report():
    """PSI-based drift report: recent request data vs training reference."""
    if REFERENCE is None:
        raise HTTPException(status_code=404, detail="No reference distributions were exported.")
    if len(_recent) < 30:
        return {"status": "insufficient_data", "rows_buffered": len(_recent),
                 "detail": "Need at least 30 predictions to assess drift."}

    df = pd.DataFrame(list(_recent))
    columns = {}
    drifted = []
    for col, ref in REFERENCE.get("numeric", {}).items():
        if col not in df.columns:
            continue
        values = pd.to_numeric(df[col], errors="coerce").dropna().to_numpy(dtype=float)
        if len(values) == 0:
            continue
        edges = np.asarray(ref["bin_edges"], dtype=float)
        counts, _ = np.histogram(np.clip(values, edges[0], edges[-1]), bins=edges)
        score = _psi(ref["bin_props"], counts / max(counts.sum(), 1))
        columns[col] = {"psi": round(score, 4), "status": _status(score)}
    for col, ref in REFERENCE.get("categorical", {}).items():
        if col not in df.columns:
            continue
        props = df[col].dropna().astype(str).value_counts(normalize=True)
        cats = list(ref.keys())
        unseen = float(sum(p for c, p in props.items() if c not in ref))
        score = _psi([ref[c] for c in cats] + [1e-4],
                     [float(props.get(c, 0.0)) for c in cats] + [unseen])
        columns[col] = {"psi": round(score, 4), "status": _status(score),
                         "unseen_category_share": round(unseen, 4)}
    drifted = [c for c, r in columns.items() if r["status"] == "drift"]
    return {
        "drifted": bool(drifted),
        "drifted_columns": drifted,
        "columns": columns,
        "rows_checked": len(df),
    }


def _psi(ref_props, new_props):
    ref = np.clip(np.asarray(ref_props, dtype=float), 1e-4, None)
    new = np.clip(np.asarray(new_props, dtype=float), 1e-4, None)
    ref, new = ref / ref.sum(), new / new.sum()
    return float(np.sum((new - ref) * np.log(new / ref)))


def _status(score):
    return "drift" if score >= 0.25 else ("warning" if score >= 0.10 else "ok")


def _to_native(value):
    """Convert numpy scalars to JSON-safe Python types."""
    if hasattr(value, "item"):
        return value.item()
    return value
